apiVersion: apps/v1
kind: Deployment
metadata:
  name: enricher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: enricher
  template:
    metadata:
      labels:
        app: enricher
    spec:
      containers:
      - name: enricher
        image: moshe5434/enricher-pizza:v1
        env:
        - name: KAFKA
          value: "kafka:9092"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MONGO_HOST
          value: "mongo"
        - name: MONGO_PORT
          value: "27017"
        - name: MONGO_DATABASE
          value: "pizza_db"
        - name: MONGO_COLLECTION
          value: "orders"